[package]
name = "jinja-rs"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
chrono = "0.4.43"
clap = { version = "4.5.54", features = ["derive"] }
dirs = "6.0.0"
glob = "0.3.3"
minijinja = "2.14.0"
rhai = { version = "1.24.0", features = ["serde", "std", "sync"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.24.0"
